version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - n 14
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh
      - echo "Build completed `date`"
      - mkdir ./open-source && touch ./open-source/NoOp
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
    - deployment/**/*
    - source/**/*
    - CHANGELOG.md
    - buildspec.yml
    - sonar-project.properties
    - .gitignore
