# Workflow that runs CDK Nag checks
name: CDK Nag Test

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  cdk-nag:
    name: CDK Nag Check
    if: ${{ (github.repository_owner != 'aws-solutions' && github.event_name == 'push') || (github.repository_owner == 'aws-solutions' && github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - run: |
          cd source/constructs && npm i --only=dev
          STACK_NAME=TestStack overrideWarningsEnabled=false npx cdk synth
