# Workflow that runs unit test
name: Unit Test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  unittest:
    name: Unit Test Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd deployment
          chmod +x ./run-unit-tests.sh && DEBUG=true ./run-unit-tests.sh